MeowPlanet/Controllers/AdoptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using MeowPlanet.Models;
using MeowPlanet.ViewModels.Adopts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;


namespace MeowPlanet.Controllers
{

    public class AdoptionController : Controller
    {
        private readonly endtermContext _context;

        public AdoptionController(endtermContext context)
        {

            _context = context;

        }

        public ActionResult Index()
        {
            var catDtoList = new List<CatsDto>();
            catDtoList = GetCatsDto(null, 0, null); //初始值: city=null, breedId=0, Sex=null
            var cats = catDtoList.OrderBy(x => Guid.NewGuid()).ToList();
            if (catDtoList.Count() > 0)
            {
                ViewBag.catid = cats.ToList()[0].CatId;
            }
            return View(cats); //排序及查詢條件

        }

        public ActionResult Next(string? city_Utf8, int breedId, bool? catSex)
        {
            var city = HttpUtility.HtmlDecode(city_Utf8);
            var catDtoList = new List<CatsDto>();
            if ((!string.IsNullOrEmpty(city) && city != "全部") || breedId != 0 || catSex != null)
            {
                //查詢條件
                catDtoList = GetCatsDto(city, breedId, catSex).OrderBy(x => Guid.NewGuid()).ToList();
                //暫存查詢條件
                ViewBag.city = (!string.IsNullOrEmpty(city) && city != "全部") ? catDtoList[0].CatCity : "全部";
                ViewBag.breedId = (breedId != 0) ? catDtoList[0].BreedId : 0;
                ViewBag.catSex = (catSex != null) ? catDtoList[0].CatSex : null;
            }
            else
            {
                catDtoList = GetCatsDto(null, 0, null).OrderBy(x => Guid.NewGuid()).ToList(); //初始值: city=null, breedId=0, Sex=null
            }
            ViewBag.catid = catDtoList[0].CatId;



            return PartialView("_CardPartial", catDtoList);
        }

        [HttpPost]
        public JsonResult Like(Adopt adopt, int catid)
        {
            //主人ID
            var owner = _context.Cats
            .Where(x => x.CatId == adopt.CatId).Select(x => x.MemberId).FirstOrDefault();
            var LoginId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);
            var memberid = LoginId;
            adopt.MemberId = memberid;
            adopt.CatId = catid;
            adopt.DateStart = DateTime.Today;
            adopt.DateOver = null;
            adopt.Status = 0;
            adopt.Owner = owner;

            _context.Adopts.Add(adopt);
            _context.SaveChanges();
            return Json(null);
        }


        public ActionResult Search(string? city_Utf8, int breedId, bool? catSex)
        {
            try
            {
                var city = HttpUtility.UrlDecode(city_Utf8); //解碼unicode
                var catDtoList = new List<CatsDto>();
                var CatsDto = GetCatsDto(city, breedId, catSex).OrderBy(x => Guid.NewGuid()).ToList(); //排序及查詢條件

                //暫存查詢條件
                ViewBag.catid = CatsDto[0].CatId;
                ViewBag.city = (!string.IsNullOrEmpty(city) && city != "全部") ? CatsDto[0].CatCity : "全部";
                ViewBag.breedId = (breedId != 0) ? CatsDto[0].BreedId : 0;
                ViewBag.catSex = (catSex != null) ? CatsDto[0].CatSex : null;

                return PartialView("_CardPartial", CatsDto);
            }
            catch
            {
                return Json(null);
            }
        }

        public List<CatsDto> GetCatsDto(string? city, int breedId, bool? catSex)
        {
            var LoginId = 0;
            if (User.FindFirst(ClaimTypes.Sid) != null)
            {
                LoginId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);
            }
            var memberid = LoginId;
            var catBreeds = _context.CatBreeds.ToList();
            //頁面上呈現品種
            ViewBag.CatBreeds = catBreeds;
            var catDtoList = new List<CatsDto>();
            var catList = new List<Cat>();
            var adopt = new List<Adopt>();
            if (memberid == 0)
            {
                catList = _context.Cats.Where(x => x.IsAdoptable == true && x.IsMissing == false).ToList();
            }
            else
            {
                catList = _context.Cats.Where(x => x.MemberId != memberid && x.IsAdoptable == true && x.IsMissing == false).ToList();
                adopt = _context.Adopts.Where(x => x.MemberId == memberid).ToList();
            }

            #region 搜尋條件判斷
            if (breedId != 0)
            {
                //品種 
                catList = catList.Where(x => x.BreedId == breedId).ToList();
            }
            if (catSex != null)
            {
                //性別
                catList = catList.Where(x => x.Sex == catSex).ToList();
            }
            if (!string.IsNullOrEmpty(city) && city != "全部")
            {
                //地點
                catList = catList.Where(x => x.City == city).ToList();
            }
            #endregion

            for (int i = 0; i < catList.Count(); i++)
            {
                if (adopt.Where(x => x.CatId == catList[i].CatId).Count() <= 0)
                {
                    var catName = catBreeds.FirstOrDefault(x => x.BreedId == catList[i].BreedId).Name;
                    var catDto = new CatsDto
                    {
                        CatId = catList[i].CatId,
                        BreedId = catList[i].BreedId,
                        MemberId = catList[i].MemberId,
                        CatName = catList[i].Name,
                        CatSex = catList[i].Sex,
                        CatAge = catList[i].Age,
                        CatIntroduce = catList[i].Introduce,
                        CatImg1 = catList[i].Img01,
                        CatImg2 = catList[i].Img02,
                        CatImg3 = catList[i].Img03,
                        CatImg4 = catList[i].Img04,
                        CatImg5 = catList[i].Img05,
                        CatIsAdoptable = catList[i].IsAdoptable,
                        BreedName = catName,
                        CatCity = catList[i].City,
                    };
                    catDtoList.Add(catDto);
                }
            }
            return catDtoList;
        }

        public ActionResult LikeTolist()
        {
            var LoginId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);
            var memberid = LoginId;
            ViewBag.MemberId = memberid;
            //申請領養列表
            var likeadopts = _context.Adopts
             .Where(x => x.MemberId == memberid)
             .Include(x => x.Cat)
             .Include(x => x.Cat.Breed)
             .Select(x => new ViewModels.LikeAdopts()
             {
                 CatName = x.Cat.Name,
                 MemberId = x.MemberId,
                 CatSex = x.Cat.Sex,
                 CatAge = x.Cat.Age,
                 BreedName = x.Cat.Breed.Name,
                 CatImg1 = x.Cat.Img01,
                 DateStart = x.DateStart,
                 DateOver = x.DateOver,
                 Status = x.Status,
                 Owner = x.Owner,
             }).OrderByDescending(x => x.DateStart).ToList();

            //送養列表         
            var ownerlist = _context.Adopts
             .Where(x => x.Owner == memberid && x.Cat.IsMissing==false)
             .Include(x => x.Member)
             .Select(x => new ViewModels.LikeAdopts()
             {
                 MemberId = x.MemberId,
                 CatId = x.CatId,
                 CatName = x.Cat.Name,
                 CatSex = x.Cat.Sex,
                 CatAge = x.Cat.Age,
                 BreedName = x.Cat.Breed.Name,
                 CatImg1 = x.Cat.Img01,
                 DateStart = x.DateStart,
                 DateOver = x.DateOver,
                 Status = x.Status,
                 Name = x.Member.Name,
             }).OrderByDescending(x => x.DateStart).ToList();
            ViewBag.owner = ownerlist;

            return PartialView("_AdoptListPartial", likeadopts);
        }

        [HttpPost]
        public JsonResult OwnerNo(int catid, int memberid)
        {

            //var ownerno = new Adopt();
            var owner = _context.Adopts.Where(x => x.CatId == catid && x.MemberId == memberid).FirstOrDefault();

            owner.DateOver = DateTime.Today;
            owner.Status = 1;

            _context.Entry(owner).State = EntityState.Modified;
            _context.SaveChanges();

            var state = "";
            if (owner.Status == 1)
            {
                state = "已拒絕";
            }
            else if (owner.Status == 2)
            {
                state = "已同意";
            }


            return Json(null);
        }

        [HttpPost]
        public JsonResult OwnerYes(int catid, int memberid)
        {
            var LoginId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);
            var owerid = LoginId;


            var clearadopt = _context.Adopts.Where(x => x.Owner == owerid && x.CatId == catid).ToList();

            for (int i = 0; i < clearadopt.Count(); i++)
            {
                if (clearadopt[i].MemberId == memberid)
                {
                    clearadopt[i].DateOver = DateTime.Today;
                    clearadopt[i].Status = 2;
                }
                else
                {
                    if (clearadopt[i].DateOver == null)
                    {
                        clearadopt[i].DateOver = DateTime.Today;
                        clearadopt[i].Status = 1;
                    }
                }
                _context.Entry(clearadopt[i]).State = EntityState.Modified;
                _context.SaveChanges();
            }


            ////把狀態等待中的都改成拒絕

MeowPlanet/Views/Adoption/Index.cshtml
@model IEnumerable<MeowPlanet.ViewModels.Adopts.CatsDto>
@using System.Security.Claims;

@{
    bool isLogin = Int32.TryParse(User.Claims.Where(x => x.Type == ClaimTypes.Sid).Select(x => x.Value).FirstOrDefault(), out int memberId);
}

@{
    ViewData["Title"] = "貓咪想家";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
<link href="~/lib/bootstrap/dist/css/animista.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="~/css/adoption.css" rel="stylesheet" />
<link href="~/css/stars.css" rel="stylesheet" />



<div id="all">
    <div id="stars"></div>
    <div id="stars2"></div>
    <div id="stars3"></div>
    <div id="stars4"></div>
    <div class="container1">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-outline-secondary select" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
            <img src="@Href("~/images/adopselect.png")" style="width:80px;border-radius:50%;" />
        </button>
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header" style="margin:auto">
                        <h5 class="modal-title" id="exampleModalLongTitle">請選擇喜歡的貓貓類型</h5>
                    </div>
                    <div class="modal-body">
                        <div class="card-body">
                            <label for="inputState">品種</label>
                            <select id="inputState" class="form-select">
                                <option selected value=0>全部</option>
                                @foreach (var item in ViewBag.CatBreeds)
                                {
                                    <option value=@item.BreedId>@item.Name</option>
                                }
                            </select>
                            <br>
                            <label for="inputState">性別</label>
                            <br />
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value=null checked>
                                <label class="form-check-label" for="inlineRadio1">全部</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value=true>
                                <label class="form-check-label" for="inlineRadio2">公</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value=false>
                                <label class="form-check-label" for="inlineRadio3">母</label>
                            </div>


                            <br>
                            <br>

                            <br>

                            <label for="inputState">地點</label>
                            <div class="form-row">
                                <div class="form-group col-4">
                                    <select id="city" class="form-select">
                                        <option selected>全部</option>
                                        <option>臺北市</option>
                                        <option>新北市</option>
                                        <option>基隆市</option>
                                        <option>新竹市</option>
                                        <option>桃園市</option>
                                        <option>新竹縣</option>
                                        <option>宜蘭縣</option>
                                        <option>臺中市</option>
                                        <option>苗栗縣</option>
                                        <option>彰化縣</option>
                                        <option>南投縣</option>
                                        <option>雲林縣</option>
                                        <option>高雄市</option>
                                        <option>臺南市</option>
                                        <option>嘉義市</option>
                                        <option>嘉義縣</option>
                                        <option>屏東縣</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <button type="button" id="search" class="btn btn-primary" data-bs-dismiss="modal">確認</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="bounce-in-top">
            <div class="box2">
                <i class="fa-solid fa-paw"></i>
            </div>
            <div class="box3">
                <i class="fa-solid fa-paw"></i>
            </div>
            <div class="box4">
                <i class="fa-solid fa-paw"></i>
            </div>
            <div class="box5">
                <i class="fa-solid fa-paw"></i>
            </div>
            <div class="cardbox">
                <div class="box1 bounce-in-top2">
                    @foreach (var item in Model)
                    {
                        <div class="autoplay col-12">
                            @if (@item.CatImg1 != null)
                            {
                                <div class="slide-1"><img src="@Url.Content(@item.CatImg1)"></div>
                            }
                            @if (@item.CatImg2 != null)
                            {
                                <div class="slide-2"><img src="@Url.Content(@item.CatImg2)"></div>
                            }
                            @if (@item.CatImg3 != null)
                            {
                                <div class="slide-3"><img src="@Url.Content(@item.CatImg3)"></div>
                            }
                            @if (@item.CatImg4 != null)
                            {
                                <div class="slide-4"><img src="@Url.Content(@item.CatImg4)"></div>
                            }
                            @if (@item.CatImg5 != null)
                            {
                                <div class="slide-5"><img src="@Url.Content(@item.CatImg5)"></div>
                            }

                        </div>

                        <div class="context trun front col-12">
                            <div class="title">@item.CatName</div>
                            <div class="a1">
                                <span>@item.BreedName</span>
                                @if (@item.CatSex == false)
                                {
                                    <i class="fa-solid fa-venus" style="color:#FF8EFF;font-size:1.3rem"></i>
                                }
                                else if (@item.CatSex == true)
                                {
                                    <i class="fa-solid fa-mars" style="color:#99b8d4;font-size:1.3rem"></i>
                                }
                                <p class="age">@item.CatAge 歲</p>
                                <p>@item.CatCity </p>
                                <p class="introduce">@item.CatIntroduce </p>
                            </div>
                        </div>

                        <div class="like" style="text-align:center; ">
                            <button id="like" onclick='checklike()' type="button" class="btn btn-outline-danger buzz-pri pulsate-bck">
                                <svg xmlns="http://www.w3.org/2000/svg" style="padding-bottom:3px;" width="18" height="18" fill="currentColor" class="bi bi-heart-fill " viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                                </svg> 認養
                            </button>
                            <button id="pass" type="button" class="btn btn-outline-secondary buzz">PASS</button>
                        </div>
                        break;
                    }
                </div>
            </div>
        </div>
    </div>



</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.1.9/sweetalert2.all.min.js"
        integrity="sha512-IZ95TbsPTDl3eT5GwqTJH/14xZ2feLEGJRbII6bRKtE/HC6x3N4cHye7yyikadgAsuiddCY2+6gMntpVHL1gHw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    //nav-item效果
    $('.nav-item a').eq(1).addClass('nav-item-active');

    //---------------------Start Event-------------------------------------
    var isLogin = '@isLogin';
    var memberId = '@memberId';
    //pass事件
    $('#pass').click(function() {

        //回傳PartialView
        $.get("@Url.Action("Next", "Adoption")", function(data) {
            $(".cardbox").empty();
            $('.cardbox').html(data);
        })
    })

    //search事件
    $('#search').click(function() {
        var breedId = $("#inputState").val();
        var catSex = document.querySelector('input[name="inlineRadioOptions"]:checked').value;
        var catCity = $("#city").val();

        //傳送資料到後端,回傳PartialView
        $.get("@Url.Action("Search", "Adoption")" + "?city_Utf8=" + escape(catCity) + "&breedId=" + escape(breedId) + "&catSex=" + escape(catSex), function(data) {
            if (data == null) {
                Swal.fire({
                    heightAuto: false,
                    position: 'center',
                    title: '無此貓貓',
                    icon: 'error',
                    showConfirmButton: false,
                    timer: 1500
                })
            } else {
                $(".cardbox").empty();
                $('.cardbox').html(data);
            }
        })
    })

    //輪播事件
    $('.autoplay').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
    });


    //---------------------End Event-------------------------------------


    //---------------------Start Function-------------------------------------

    //like事件
    function checklike() {
        checkLogin(() => {
            Swal.fire({
                title: "確認要領養貓貓嗎？",
                text: "確認申請領養後不可取消，請慎重考慮！",
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#B99668',
                cancelButtonColor: '#4B5461',
                confirmButtonText: '申請'
            }).then(function(result) {
                if (result.value) {
                    Swal.fire(
                        '已申請領養！',
                        '請等候貓貓主人確認申請',
                        'success'
                    ).then(function(result) {
                        $.ajax({
                            method: 'post',
                            url: '/Adoption/Like',
                            data: { catid: @ViewBag.catid},
                            dataType: 'json',
                            success: function(data) {
                                window.location.reload();
                            },
                            error: function() {
                                window.location.reload();
                            }
                        });
                    }
                    )
                }
            })
        })


    }


    //檢查登入
    function checkLogin(action) {

        if (isLogin == "False") {
            Swal.fire({
                title: '請登入會員以執行此操作',
                text: '是否要前往登入頁面?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: '前往登入',
                cancelButtonText: '下次一定',
                heightAuto: false,
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = "/Login";
                }
                else {
                    return false
                }
            })
        }
        else {
            action();
        }
    }

         //---------------------End Function-------------------------------------

</script>

MeowPlanet/Views/Adoption/_CardPartial.cshtml
@model IEnumerable<MeowPlanet.ViewModels.Adopts.CatsDto>
@using System.Security.Claims;


@{
    bool isLogin = Int32.TryParse(User.Claims.Where(x => x.Type == ClaimTypes.Sid).Select(x => x.Value).FirstOrDefault(), out int memberId);
}

<div class="box1 rotate-vert-center">
    @foreach (var item in Model)
    {
            <div class="autoplay col-12">
            @if (@item.CatImg1 != null)
            {
                        <div class="slide-1"><img src="@Url.Content(@item.CatImg1)"></div>
            }
            @if (@item.CatImg2 != null)
            {
                        <div class="slide-2"><img src="@Url.Content(@item.CatImg2)"></div>
            }
            @if (@item.CatImg3 != null)
            {
                        <div class="slide-3"><img src="@Url.Content(@item.CatImg3)"></div>
            }
            @if (@item.CatImg4 != null)
            {
                        <div class="slide-4"><img src="@Url.Content(@item.CatImg4)"></div>
            }
            @if (@item.CatImg5 != null)
            {
                        <div class="slide-5"><img src="@Url.Content(@item.CatImg5)"></div>
            }

            </div>

            <div class="context trun front col-12">
                <div class="title">@item.CatName</div>
                <div class="a1">
                    <span>@item.BreedName</span>
                @if (@item.CatSex == false)
                {
                            <i class="fa-solid fa-venus" style="color:#FF8EFF;font-size:1.3rem"></i>
                }
                else if (@item.CatSex == true)
                {
                            <i class="fa-solid fa-mars" style="color:#99b8d4;font-size:1.3rem"></i>
                }
                    <p class="age">@item.CatAge 歲</p>
                    <p>@item.CatCity </p>
                    <p class="introduce">@item.CatIntroduce </p>
                </div>
            </div>

            <div class="like" style="text-align:center; ">
                <button id="like"  onclick='checklike2()' type="button" class="btn btn-outline-danger buzz-pri pulsate-bck">
                    <svg xmlns="http://www.w3.org/2000/svg" style="padding-bottom:3px;" width="18" height="18" fill="currentColor" class="bi bi-heart-fill " viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                    </svg> 認養
                </button>
                <button id="pass" type="button" class="btn btn-outline-secondary buzz">PASS</button>
            </div>
        break;
    }
</div>

<script>
    
//---------------------Start Event-------------------------------------
    
    //pass事件
    $('#pass').click(function() {

        //後端傳的bool會呈現字串True以及False, 所以要手動轉換
        var catSex = null;
        if ("@ViewBag.catSex" == "True" || "@ViewBag.catSex" == "False" ) { 
        
            catSex = ("@ViewBag.catSex" == "True") ?true: false;
        }

        //傳送資料到後端,回傳PartialView
        $.get("@Url.Action("Next", "Adoption")"+"?city_Utf8="+escape("@ViewBag.city")+ "&breedId="+escape(@ViewBag.breedId)+ "&catSex=" + escape(catSex) , function(data) {
            $(".cardbox").empty();
            $('.cardbox').html(data);
        })
    })

    //輪播事件
    $('.autoplay').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
    });


//---------------------End Event-------------------------------------


//---------------------Start Function-------------------------------------

    //like事件
    function checklike2() {
        checkLogin(() => {
            Swal.fire({
                title: "確認要領養貓貓嗎？",
                text: "確認申請領養後不可取消，請慎重考慮！",
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#B99668',
                cancelButtonColor: '#4B5461',
                confirmButtonText: '申請'
            }).then(function(result) {
                if (result.value) {
                    Swal.fire(
                        '已申請領養！',
                        '請等候貓貓主人確認申請',
                        'success'
                    ).then(function(result) {
                        $.ajax({
                            method: 'post',
                            url: '/Adoption/Like',
                            data: { catid: @ViewBag.catid},
                            dataType: 'json',
                            success: function(data) {
                                window.location.reload();
                            },
                            error: function() {
                                window.location.reload();
                            }
                        });
                    }
                    )
                }
            })
        })


    }

        //檢查登入
    function checkLogin(action) {

        if (isLogin == "False") {
            Swal.fire({
                title: '請登入會員以執行此操作',
                text: '是否要前往登入頁面?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: '前往登入',
                cancelButtonText: '下次一定',
                heightAuto: false,
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = "/Login";
                }
                else {
                    return false
                }
            })
        }
        else {
            action();
        }
    }
 //---------------------End Function-------------------------------------

    

    
    

    


</script>

MeowPlanet/Views/Adoption/_OwnerPartial.cshtml
@model IEnumerable<MeowPlanet.ViewModels.LikeAdopts>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
<link href="~/lib/bootstrap/dist/css/animista.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />

@{
    string status = "";
    string date = "";

}


@foreach (var item in Model)
{
    <div class="row clue-item p-3 me-3">
        <div class="col-3">
            <img src="@Url.Content(@item.CatImg1)">
        </div>
        <div class="col-5 detail">
            <p>@item.CatName</p>
            <p>
                @item.BreedName
                @if (@item.CatSex == false)
                {
                    <i class="fa-solid fa-venus" style="color:#FF8EFF;font-size:1.3rem"></i>
                }
                else if (@item.CatSex == true)
                {
                    <i class="fa-solid fa-mars" style="color:#99b8d4;font-size:1.3rem"></i>
                }
            </p>
            <p>@item.CatAge 歲</p>

            <p>
                @if (@item.DateOver == null)
                {
                    date = "申請日期:" + @item.DateStart.ToShortDateString();
                }
                else
                {
                    date = "結束日期:" + @item.DateOver.Value.ToShortDateString();
                }
                @date
            </p>
            <p>
                狀態:
                @if (@item.Status == 0)
                {
                    status = "等待中";
                }
                else if (@item.Status == 1)
                {
                    status = "已拒絕";
                }
                else
                {
                    status = "已同意";
                }
                @status
            </p>
        </div>

    </div>


}