MeowPlanet/Models/Sitter.cs
using System;
using System.Collections.Generic;

namespace MeowPlanet.Models
{
    public partial class Sitter
    {
        public Sitter()
        {
            Favorites = new HashSet<Favorite>();
            Orderlists = new HashSet<Orderlist>();
            SitterFeatures = new HashSet<SitterFeature>();
        }

        public int ServiceId { get; set; }
        public int MemberId { get; set; }
        public string Name { get; set; } = null!;
        public string Summary { get; set; } = null!;
        public int Pay { get; set; }
        public string Licence { get; set; } = null!;
        public string Cage { get; set; } = null!;
        public string Monitor { get; set; } = null!;
        public string Meal { get; set; } = null!;
        public string CatNumber { get; set; } = null!;
        public decimal PosLat { get; set; }
        public decimal PosLng { get; set; }
        public bool IsService { get; set; }
        public decimal AvgStar { get; set; }
        public string? Img01 { get; set; }
        public string? Img02 { get; set; }
        public string? Img03 { get; set; }
        public string? Img04 { get; set; }
        public string? Img05 { get; set; }
        public string? Area1 { get; set; }
        public string? Area2 { get; set; }
        public string? Area3 { get; set; }
        public string? FormattedAddress { get; set; }

        public virtual Member Member { get; set; } = null!;
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<Orderlist> Orderlists { get; set; }
        public virtual ICollection<SitterFeature> SitterFeatures { get; set; }
    }
}

MeowPlanet/ViewModels/Missings/DetailViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MeowPlanet.ViewModels.Missings
{
    public class DetailViewModel
    {
        public int? MissingId { get; set; }
        public string? Name { get; set; }
        public bool? Sex { get; set; }
        public int? Age { get; set; }
        public string? Breed { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }
        public string? Img01 { get; set; }
        public string? Img02 { get; set; }
        public string? Img03 { get; set; }

        public string? Description { get; set; }
        public int MemberId { get; set; }
        public string? MemberName { get; set; }
        public string? Photo { get; set; }

    }
}

MeowPlanet/ViewModels/SitterViewModels.cs
using MeowPlanet.Models;
namespace MeowPlanet.ViewModels
{
    public class SitterViewModels
    {
        public Sitter? sitter { get; set; }

        public string? memberPhoto { get; set; }

        public List<string>? sitterfeatureList { get; set; }

        public List<Orderlist>? OrderCommentList { get; set; }
    }
}

MeowPlanet/ViewModels/Sitters/SitterComfirmPayViewModels.cs
namespace MeowPlanet.ViewModels.Sitters
{
    public class SitterComfirmPayViewModels
    {
        //保姆本人資料
        public string SitterName { get; set; } = null!;
        public string? SitterPhoto { get; set; }
        //使用者本人資料
        public string UserName { get; set; } = null!;
        public string UserPhone { get; set; } = null!;
        public string? UserPhoto { get; set; }
        //選擇貓咪資料
        public int CatId { get; set; }
        public bool? Sex { get; set; }
        public string? Introduce { get; set; }
        public string BreedName { get; set; } = null!;
        public string? CatName { get; set; }
        public string? CatImg01 { get; set; }
        //服務基本資料
        public int ServiceId { get; set; }
        public string ServiceName { get; set; } = null!;
        public DateTime DateStart { get; set; }
        //Wed Aug 03 2022 00:00:00 GMT+0800
        public DateTime DateOver { get; set; }
        public int Pay { get; set; }
        public int Night { get; set; }
        public int Total { get; set; }


    }
}

MeowPlanet/ViewModels/Sitters/SitterRecordViewModel.cs
namespace MeowPlanet.ViewModels.Sitters
{
    public class SitterRecordViewModel
    {

        //保姆本人資料

        //訂單ID
        public int OrderId { get; set; }
        //保姆姓名
        public string SitterName { get; set; } = null!;
        //保姆電話
        public string SitterPhone { get; set; } = null!;
        //保姆照片
        public string? SitterPhoto { get; set; }
        //保姆地址
        public string? FormattedAddress { get; set; }
        //訂單入宿開始日期
        public DateTime DateStart { get; set; }
        //Wed Aug 03 2022 00:00:00 GMT+0800
        //訂單入宿結束日期
        public DateTime DateOver { get; set; }
        //貓咪姓名
        public string? CatName { get; set; }
        //訂單費用
        public int Total { get; set; }
        //訂單狀態
        public int Status { get; set; }
    }
}

MeowPlanet/ViewModels/Sitters/SitterViewModels.cs
using MeowPlanet.Models;

namespace MeowPlanet.ViewModels.Sitters
{
    public class SitterViewModels
    {
        public Sitter? sitter { get; set; }

        public string? memberPhoto { get; set; }

        public List<string>? sitterfeatureList { get; set; }

        public List<Orderlist>? OrderCommentList { get; set; }

        public List<Member>? CommentOfUserList { get; set; }

        public List<Cat>? usercatList { get; set; }

        
    }
}

MeowPlanet/ViewModels/Sitters/SitterWorkViewModel.cs
namespace MeowPlanet.ViewModels.Sitters
{
    public class SitterWorkViewModel
    {

        //使用者本人資料
        public string UserName { get; set; } = null!;
        public string UserPhone { get; set; } = null!;
        public string? UserPhoto { get; set; }
        //選擇貓咪資料
        public int OrderId { get; set; }
        public bool? Sex { get; set; }
        public string? Introduce { get; set; }
        public string BreedName { get; set; } = null!;
        public string? CatName { get; set; }
        public string? CatImg01 { get; set; }
        public DateTime DateStart { get; set; }
        //Wed Aug 03 2022 00:00:00 GMT+0800
        public DateTime DateOver { get; set; }
        public int Total { get; set; }
        public int Status { get; set; }







    }
}

MeowPlanet/Controllers/SitterController.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
using Microsoft.AspNetCore.Mvc;
using MeowPlanet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis;
using System.Security.Claims;
using MeowPlanet.ViewModels.Sitters;


namespace MeowPlanet.Controllers
{
    public class SitterController : Controller
    {
        private readonly endtermContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly int? _memberId;

        public SitterController(endtermContext context, IHttpContextAccessor contextAccessor, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;

            if (contextAccessor.HttpContext.User.FindFirst(ClaimTypes.Sid) != null)
            {
                _memberId = Convert.ToInt32(contextAccessor.HttpContext.User.FindFirst(ClaimTypes.Sid).Value);
            }
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            //三個方法用中斷點看持續時間幾乎都差不多，大概2.5s~3.0s之間跳動
            //但單純看sql語法的秒數又差很多
            //方法一、二的sql 語法速度大概是70ms~90ms
            //方法三的sql 語法速度加總大概 280ms 以上
            //想要用forloop來測試 10圈的速度
            //發現第一圈花了2.X秒，其餘圈數都花<100ms左右而已
            //.AsNoTrackingWithIdentityResolution()
            //.Include(c => c.SitterFeatures)

            //方法一
            var result = await _context.Sitters
                .AsNoTracking()
                .Where(m => m.IsService == true)
                .Select(m => new SitterViewModels
                {
                    sitter = m,
                    memberPhoto = m.Member.Photo,
                    sitterfeatureList = m.SitterFeatures.Select(m => m.Feature.Name).ToList(),
                    OrderCommentList = m.Orderlists.ToList(),
                }).ToListAsync();

            //方法二
            //var result = new List<Sitter>();
            //result = await _context.Sitters
            //.Where(m => m.IsService == true).ToListAsync();

            //List<SitterViewModels> result2 = new List<SitterViewModels>();
            //foreach (var item in result)
            //{
            //    SitterViewModels x = new SitterViewModels()
            //    {
            //        sitter = item,
            //        memberPhoto = item.Member.Photo,
            //        sitterfeatureList = item.SitterFeatures.Select(c => c.Feature.Name).ToList(),
            //        OrderCommentList = item.Orderlists.ToList(),
            //    };
            //    result2.Add(x);
            //};

            //方法三
            //List<SitterViewModels> result = new List<SitterViewModels>();
            //var sitterList = _context.Sitters.Where(m => m.IsService == true).ToList();
            //foreach (var item in sitterList)
            //{
            //    SitterViewModels model = new SitterViewModels()
            //    {
            //        sitter = item,
            //        sitterfeatureList = _context.SitterFeatures.Include(m => m.Feature).Where(m => m.ServiceId == item.ServiceId).Select(x => x.Feature.Name).ToList(),
            //        OrderCommentList = _context.Orderlists.Where(m => m.ServiceId == item.ServiceId).ToList(),
            //        memberPhoto = _context.Members.FirstOrDefault(m => m.MemberId == item.MemberId).Photo,

            //    };
            //    result.Add(model);
            //}

            //TempData["controller"] = "Sitter";
            //TempData["action"] = "Index";

            return View(result);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            var result = await _context.Sitters
                .AsNoTracking()
                //.AsNoTrackingWithIdentityResolution()
                .Where(m => m.ServiceId == id)
                .Select(m => new SitterViewModels
                {
                    sitter = m,
                    memberPhoto = m.Member.Photo,
                    sitterfeatureList = m.SitterFeatures.Select(m => m.Feature.Name).ToList(),
                    OrderCommentList = m.Orderlists.Where(m => m.Status == 2).OrderByDescending(m => m.DateOver).ToList(),
                    CommentOfUserList =m.Orderlists.Where(m => m.Status == 2).OrderByDescending(m => m.DateOver).Select(m => m.Member).ToList(),
                }).FirstOrDefaultAsync();


            var catList = await _context.Cats
                .Where(m => m.MemberId == _memberId)
                .Select(m => new Cat
                {
                    CatId = m.CatId,
                    BreedId = m.BreedId,
                    IsAdoptable = m.IsAdoptable,
                    IsMissing = m.IsMissing,
                    IsSitting = m.IsSitting,
                    Name = m.Name,
                    Sex = m.Sex,
                    Introduce = m.Introduce,
                    Img01 = m.Img01,
                }).ToListAsync();

            ViewBag.catList = catList;

            //TempData["controller"] = "Sitter";
            //TempData["action"] = "Detail";
            //TempData["ids"] = $"{id}";

            return View(result);
        }
        //方法一
        // 使用 變數 來接收submit資料
        [HttpPost]
        public ActionResult ComfirmPay(string startDate, string endDate, int night, int catId, int serviceId)
        {
            var user = _context.Members
                .Include(c => c.Cats.Where(c => c.CatId == catId))
                .ThenInclude(c => c.Breed)
                .Where(c => c.MemberId == _memberId)
                .FirstOrDefault();

            var sitter = _context.Sitters
                .Include(c => c.SitterFeatures)
                .Include(c => c.Member)
                .Where(c => c.ServiceId == serviceId).FirstOrDefault();

            SitterComfirmPayViewModels result = new SitterComfirmPayViewModels()
            {
                SitterName = sitter.Member.Name,
                SitterPhoto = sitter.Member.Photo,
                UserName = user.Name,
                UserPhone = user.Phone,
                UserPhoto = user.Photo,
                CatId = catId,
                Sex = user.Cats.FirstOrDefault().Sex,
                Introduce = user.Cats.FirstOrDefault().Introduce,
                BreedName = user.Cats.FirstOrDefault().Breed.Name,
                CatName = user.Cats.Where(c => c.CatId == catId).FirstOrDefault().Name,
                CatImg01 = user.Cats.Where(c => c.CatId == catId).FirstOrDefault().Img01,
                ServiceId = serviceId,
                ServiceName = sitter.Name,
                DateStart = DateTime.ParseExact(startDate, "yyyy-MM-ddTHH:mm:ss.fffZ", System.Globalization.CultureInfo.InvariantCulture).Date,
                DateOver = DateTime.ParseExact(endDate, "yyyy-MM-ddTHH:mm:ss.fffZ", System.Globalization.CultureInfo.InvariantCulture).Date,
                Pay = sitter.Pay,
                Night = night,
                Total = night * sitter.Pay,
            };
            return View(result);
        }
        //方法二
        // 使用 IFormCollection 來接收submit資料
        //[HttpPost]
        //public ActionResult ComfirmPay(IFormCollection form)
        //{
        //    string startDate = form["startDate"].ToString();
        //    string endDate = form["endDate"].ToString();
        //    //string endDate = form["__RequestVerificationToken"].ToString();

        //    ViewBag.start = startDate;
        //    ViewBag.end = endDate;
        //    return View();
        //}
        
        //送出訂單
        [HttpPost]
        public async Task<IActionResult> AddOrder(SitterComfirmPayViewModels sitterComfirmPay)
        {
            Orderlist orderlist = new Orderlist()
            {
                MemberId = (int)_memberId,
                ServiceId = sitterComfirmPay.ServiceId,
                CatId = sitterComfirmPay.CatId,
                DateStart = sitterComfirmPay.DateStart,
                DateOver = sitterComfirmPay.DateOver,
                DateOrder = DateTime.Now,
                Total = sitterComfirmPay.Total,
            };
            _context.Orderlists.Add(orderlist);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<ActionResult> SitterBox()
        {
            var sitter = await _context.Sitters
             .Where(x => x.MemberId == _memberId)
             .Select(x => new SitterViewModels
             {
                 sitter = x,
                 sitterfeatureList = x.SitterFeatures.Select(x => x.Feature.Name).ToList(),
             }).FirstOrDefaultAsync();
            return PartialView("_SitterBoxPartial",sitter);
        }

        [HttpGet]
        public  async Task<ActionResult> SitterViewMode()
        {
            var sitter = await _context.Sitters
            //要用theninclude 才看的到 feature
             //.Include(x => x.SitterFeatures)
             //.ThenInclude(x => x.Feature)
             //直接 include 看不到 feature
             //.Include(x => x.SitterFeatures.Feature)
             .Where(x => x.MemberId == _memberId)
             .Select( x => new SitterViewModels
             {
               sitter = x,
               //實際測試 我根本不用上面的include就可以取到我要資料了，這串語法自帶LEFT JOIN 跟 INNER JOIN
               sitterfeatureList = x.SitterFeatures.Select(x => x.Feature.Name).ToList(),
             }).FirstOrDefaultAsync();
 
            return PartialView("_SitterViewModePartial",sitter);
        }

        [HttpPost]
        public ActionResult SitterEditMode([FromBody]SitterViewModels j)
        {
            return PartialView("_SitterEditModePartial", j);
        }

        [HttpPost]
        public async Task<ActionResult> SaveSitter(SitterViewModels j, List<string> check, IFormFile file1, IFormFile file2, IFormFile file3, IFormFile file4, IFormFile file5)
        {
            var sitterDB = await _context.Sitters

MeowPlanet/Views/Sitter/ComfirmPay.cshtml
@model  MeowPlanet.ViewModels.Sitters.SitterComfirmPayViewModels;
@{
    ViewData["Title"] = "預約明細";
}
@section Styles{
    <link  href="~/css/sitter-comfirmpay.css" rel="stylesheet"/>
}


<div class="starsky">
    <div id="stars"></div>
    <div id="stars2"></div>
    <div id="stars3"></div>
    <div class="order-rec_div01">
        <!-- 會員主人 -->
        <div class="user-info_div02">
            <!-- 保姆-->
            <div class="rec_div7">
                <div class="info-rec">
                    <div class="title_div7-1">
                        您預約的保姆
                    </div>
                    <div class="content_div7-2 ">
                        <div>姓名 : @Model.SitterName</div>
                        <div>電話 : (於保姆確認後顯示電話)</div>
                        <div>地址 : (於保姆確認後顯示地址)</div>
                    </div>
                </div>
                <img src="@Model.SitterPhoto" alt="">
            </div>
            <div class="hr-line"></div>

            <!-- 主人 -->
            <div class="rec_div7">
                <div class="info-rec">
                    <div class="title_div7-1">
                        您的聯絡資訊
                    </div>
                    <div class="content_div7-2">
                        <div>姓名 : @Model.UserName</div>
                        <div>電話 : @Model.UserPhone</div>
                    </div>
                </div>
                <img src="@Model.UserPhoto">
            </div>

            <div class="hr-line"></div>

            <!--喵咪 -->
            <div class="rec-last_div7">
                <div class="info-rec">
                    <div class="title_div7-1">
                        您所選的貓咪
                    </div>
                    <div class="content_div7-2">
                        <div>
                            姓名 : @Model.CatName
                            &nbsp&nbsp
                            @if(@Model.Sex == true)
                            {
                                <i class="fa-solid fa-mars" style="color:#99b8d4;font-size:1.3rem"></i>
                            }
                            else
                            {
                                <i class="fa-solid fa-venus" style="color:#FF8EFF;font-size:1.3rem"></i>
                            }
                        </div>
                        <div style="display: flex;">
                            <div class="self-intro-tag_div5-2-1">貓<br />咪<br />介<br />紹</div>
                            <div class="self-intro_div5-2-2">
                                @Model.Introduce
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cat_div6">
                    <img src="@Model.CatImg01">
                    <div>品種 : @Model.BreedName</div>
                </div>
            </div>
        </div>
    
        <!-- 訂單細項 -->
        <div class="order-info_div03">
            <div class="order-detail_div05">
                <div class="order-title_div9">預約明細</div>
                <div class="order-content_div10">
                    <div>保姆姓名 &nbsp : &nbsp @Model.ServiceName</div>
                    <div>開始日期 &nbsp : &nbsp @Model.DateStart.ToString("d")</div>
                    <div>結束日期 &nbsp : &nbsp @Model.DateOver.ToString("d")</div>
                    <div>單日費用 &nbsp : &nbsp TWD $ @Model.Pay</div>
                    <div>入住天數 &nbsp : &nbsp 共 &nbsp @Model.Night &nbsp 日 </div>
                </div>
                <div class="order-total_div11">TWD $ @Model.Total</div>
            </div>
            <div class="btn-rec_div06">
                <form method="post" asp-action="AddOrder" asp-controller="Sitter">
                    <input type="hidden" asp-for="ServiceId" value="@Model.ServiceId"/>
                    <input type="hidden" asp-for="CatId" value="@Model.CatId"/>
                    <input type="hidden" asp-for="DateStart" value="@Model.DateStart"/>
                    <input type="hidden" asp-for="DateOver" value="@Model.DateOver"/>
                    <input type="hidden" asp-for="Total" value="@Model.Total"/>
                    <button type="submit" class="yes_div12">預&nbsp&nbsp約</button>
                    <button type="button" class="cancel_div13">取&nbsp&nbsp消</button>
                </form>
            </div>
        </div>
    </div>
</div>

    @section Scripts{
        <script>
            $('.cancel_div13').click(function(){
                window.location.href = "/Sitter/Detail/@Model.ServiceId";
            })
        </script>
    }

MeowPlanet/Views/Sitter/Index.cshtml
@using MeowPlanet.ViewModels.Sitters;
@model IEnumerable<SitterViewModels>;
@section Styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css" />
    <link href="~/css/sitter-index.css" rel="stylesheet" />
}
@{
    ViewData["Title"] = "貓咪保姆";
}
<div class="input-box">
        <input class="buzz" type="text" id="mapInput" placeholder="想在哪裡找保姆呢...">
    </div>
<div style="position:relative;overflow:hidden;">
    <!-- 地圖顯示區 -->
    <div class="show-map_div2-1" id="btn01">
        <img id="btn01" src="@Href("~/images/sitter/顯示地圖.png")">
    </div>
    <div class="map_div2-2" id="map_div01">
        <div id="map"></div>
        <div class="close-map_div2-2-1" id="btn02">
            <i class="fa-solid fa-angles-left fa-lg"></i>
        </div>
    </div>
    <!-- 背景 -->
    <div class="starsky">
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>

        <!-- 保姆展示細項 -->
        <div class="container" id="search-result_div03">
            <div class="row">
                
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var model = @Html.Raw(Json.Serialize(Model));
        $('.nav-item a').eq(0).addClass('nav-item-active');
    </script>
    <script src="~/js/sitter-index.js" type="module"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5GLU-Md1jCttuMgYGiLngvDh0nELvLjM&callback=initMap&libraries=places,geometry"></script>
    }

MeowPlanet/Views/Sitter/_SitterBoxPartial.cshtml
<style>
.nav-tabs {
    border: 0px solid;
}

.nav-tabs .nav-link {
    border-radius: 20px;
}

    .nav-tabs .nav-item.show .nav-link,
    .nav-tabs .nav-link.active {
        font-weight: bold;
        font-size: 21px;
        border-radius: 20px;
        width: 200px;
        background-color: rgb(255, 255, 255);
        border: 2.5px rgb(255, 255, 255) solid;
        color: #000000;
    }

.nav-link {
    color: rgb(255, 255, 255);
    width: 200px;
    font-size: 21px;
    border-radius: 20px;
    border: 2.5px rgb(255, 255, 255) solid;
}

    .nav-link:focus,
    .nav-link:hover {
        color: #FFF;
    }
</style>

<div class="div1">
    <ul class="nav nav-tabs d-flex justify-content-center" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" type="button">
                <i class="fa-solid fa-address-card"></i> &nbsp 基本資料
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" type="button">
                <i class="fa-solid fa-briefcase"></i> &nbsp 工作管理
            </button>
        </li>
    </ul>
    <div id="sitterContent">
        <partial name="_SitterViewModePartial" />
    </div>
</div>
<script>
     $('#home-tab').click(() => {
        $.get('/Sitter/SitterViewMode', function(data) {
            $('#sitterContent').html(data);
        })
    })

    $('#profile-tab').click(() => {
        $.get('/Sitter/SitterWorkManage', function(data) {
            $('#sitterContent').html(data);
        })
    })
</script>